#App\Entity\Product:
#  properties:
#    name:
#      - NotBlank: { message: "Le nom du produit est oblogatoire" }
#     - Lenght:
#      {
#       min: 3,
#      max: 255,
#     minMessage: "Le nom du produit doit faire plus de 3 caractères",
#  }
#Price:
# - NotBlank: { message: "Le prix du produit est obligatoire" }
